# Generated by Django 4.1 on 2022-09-27 13:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('delete_flag', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True, null=True)),
                ('dob', models.DateField()),
                ('year', models.IntegerField(default=0)),
                ('phonenumber', models.CharField(max_length=12)),
                ('weight', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=20)),
                ('usaw', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('school', models.CharField(max_length=250)),
                ('contact', models.CharField(max_length=250)),
                ('contactnumber', models.CharField(max_length=12)),
                ('gpa', models.DecimalField(decimal_places=2, default=2.0, max_digits=3)),
                ('transcript', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('goals', models.CharField(blank=True, max_length=400, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('barcode', models.ImageField(blank=True, default='', upload_to='barcodes/')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('delete_flag', models.IntegerField(default=0)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('delete_flag', models.IntegerField(default=0)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
                ('classes', models.ManyToManyField(blank=True, to='athletes.classtime')),
            ],
            options={
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Eventsignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.CharField(choices=[('Team', 'Travel with the Team'), ('Parents', 'Travel with Parents')], max_length=250)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.event')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='events',
            field=models.ManyToManyField(blank=True, to='athletes.event'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.groups'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('athlete_id', models.CharField(default='0', max_length=200)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=datetime.time)),
                ('mark_attendance', models.CharField(choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], default='Absent', max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('classtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.classtime')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.groups')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
                'unique_together': {('athlete_id', 'classtime', 'date')},
            },
        ),
    ]
