# Generated by Django 4.1 on 2022-09-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
