# Generated by Django 4.1 on 2022-09-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_alter_athlete_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='stripe_price_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='stripe_product_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventsignup',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
